1. Importar bibliotecas

In [210]:
import pandas as pd
import numpy as np

2. Load o dataset

In [213]:
df = pd.read_csv("C:/Users/gisel/Downloads/netflix_titles.csv/netflix_titles.csv")

3. Olhada inicial

In [216]:
#Primeiras linhas do dataset
print('Primeiras linhas:')
display(df.head())

#Últimas linhas do dataset
print("\nÚltimas linhas:")
display(df.tail())

# Resumo do dataset
print("\nResumo:")
df.info()

# Número de linhas e colunas
print("\nShape do dataset:", df.shape)

Primeiras linhas:

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

Últimas linhas:

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

Resumo:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

Shape do dataset: (8807, 12)

4. Padronização dos dados

In [250]:
#Conversão de tipo de dados
df['date_added'] = pd.to_datetime(df['date_added'], format='mixed')

#Separar duration em 2 colunas
df[['duration_value', 'duration_unit']] = df['duration'].str.split(' ', n=1, expand=True)

# Converter duration_value para númerico
df['duration_value'] = pd.to_numeric(df['duration_value'])

#Checar resultado
df[['duration', 'duration_value', 'duration_unit']].head()

    duration  duration_value duration_unit
0     90 min              90           min
1  2 Seasons               2       Seasons
2   1 Season               1        Season
3   1 Season               1        Season
4  2 Seasons               2       Seasons

In [220]:
#Convertendo textos para minúsculos
colunas_texto = ['type', 'listed_in', 'rating', 'duration_unit']

#Aplicando
df[colunas_texto] = df[colunas_texto].apply(lambda col: col.str.lower())

#Verificar
df[['type', 'listed_in', 'rating', 'duration_unit']].head()

,type,listed_in,rating,duration_unit
0,movie,documentaries,pg-13,min
1,tv show,"international tv shows, tv dramas, tv mysteries",tv-ma,seasons
2,tv show,"crime tv shows, international tv shows, tv act...",tv-ma,season
3,tv show,"docuseries, reality tv",tv-ma,season
4,tv show,"international tv shows, romantic tv shows, tv ...",tv-ma,seasons

5. Limpeza dos dados

In [222]:
#Valores nulos em director
print('Valores nulos em director:', df['director'].isna().sum())

#Valores nulos em cast
print('Valores nulos em cast:', df['cast'].isna().sum())

#Valores nulos em rating
print('Valores nulos em rating:', df['rating'].isna().sum())

Valores nulos em director: 2634
Valores nulos em cast: 825
Valores nulos em rating: 4

In [223]:
#Checando por dulplicates
print('Duplicados:', df.duplicated().sum())

#Preenchendo valores nulos em director, cast, rating
df.fillna({
    'director': 'unknow',
    'cast': 'unknow',
    'rating': 'not_rated'
}, inplace=True)

#Drop rows onde date_added é nulo por que precisamos de mês e ano para análise futura e so temos ano para preencher
df.dropna(subset=['date_added'], inplace=True)

#Verificando limpeza
df.info()

Duplicados: 0
<class 'pandas.core.frame.DataFrame'>
Index: 8797 entries, 0 to 8806
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   show_id         8797 non-null   object
 1   type            8797 non-null   object
 2   title           8797 non-null   object
 3   director        8797 non-null   object
 4   cast            8797 non-null   object
 5   country         7967 non-null   object
 6   date_added      8797 non-null   datetime64[ns]
 7   release_year    8797 non-null   int64
 8   rating          8797 non-null   object
 9   duration        8794 non-null   object
 10  listed_in       8797 non-null   object
 11  description     8797 non-null   object
 12  duration_value  8794 non-null   float64
 13  duration_unit   8794 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(1), object(11)
memory usage: 1.0+ MB

In [248]:
#Verificando valores
df['rating'].unique()

#ERRO EM RATING(VALORES PERTECEM EM DURATION)
df[df['duration'].isna()]

# 1. Preencher duration com rating, mas só onde duration está nulo
df.loc[df["duration"].isna(), "duration"] = df["rating"]

# 2. Agora, limpar o rating apenas dessas linhas (onde houve a correção)
df.loc[df.index[df["rating"] == df["duration"]], "rating"] = None

#Verificando
df[df['duration'].isna()]
df['rating'].unique()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8765 entries, 0 to 8806
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   show_id         8765 non-null   object
 1   type            8765 non-null   object
 2   title           8765 non-null   object
 3   director        8765 non-null   object
 4   cast            8765 non-null   object
 5   country         8765 non-null   object
 6   date_added      8765 non-null   datetime64[ns]
 7   release_year    8765 non-null   int64
 8   rating          8762 non-null   object
 9   duration        8765 non-null   object
 10  listed_in       8765 non-null   object
 11  description     8765 non-null   object
 12  duration_value  8762 non-null   float64
 13  duration_unit   8762 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(1), object(11)
memory usage: 1.3+ MB

In [256]:
#Preencher country baseado em director

mapeamento = df.dropna(subset=["country"]).set_index("director")["country"].to_dict()
df["country"] = df["country"].fillna(df["director"].map(mapeamento))

#ainda existem valores nulos, podemos preencher a partir do cast

# Função para preencher country usando cast
def preencher_country_por_cast(df, cast_col="cast", country_col="country"):
    # Criar mapeamento de ator -> país com base em linhas que já têm country
    mapeamento_atores = {}
    for _, row in df.dropna(subset=[country_col]).iterrows():
        atores = [a.strip() for a in row[cast_col].split(",")]
        for ator in atores:
            mapeamento_atores[ator] = row[country_col]
    
    # Preencher country nas linhas nulas
    def buscar_pais(row):
        if pd.notna(row[country_col]):
            return row[country_col]
        atores = [a.strip() for a in row[cast_col].split(",")]
        for ator in atores:
            if ator in mapeamento_atores:
                return mapeamento_atores[ator]
        return np.nan
    
    df[country_col] = df.apply(buscar_pais, axis=1)
    return df

# Aplicar a função
df = preencher_country_por_cast(df)
print(df.info())

#Quase 200 registros sem paises, podemos dropar essas linhas
df.dropna(subset=['country'], inplace=True)

<class 'pandas.core.frame.DataFrame'>
Index: 8765 entries, 0 to 8806
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   show_id         8765 non-null   object
 1   type            8765 non-null   object
 2   title           8765 non-null   object
 3   director        8765 non-null   object
 4   cast            8765 non-null   object
 5   country         8765 non-null   object
 6   date_added      8765 non-null   datetime64[ns]
 7   release_year    8765 non-null   int64
 8   rating          8762 non-null   object
 9   duration        8765 non-null   object
 10  listed_in       8765 non-null   object
 11  description     8765 non-null   object
 12  duration_value  8765 non-null   int64
 13  duration_unit   8765 non-null   object
dtypes: datetime64[ns](1), int64(2), object(11)
memory usage: 1.3+ MB
None

In [3]:
# Salvar novo dataset
df.to_csv("C:/Users/gisel/Downloads/netflix_titles.csv/netflix_titles_clean.csv", index=False)

NameError: name 'df' is not defined

In [260]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,duration_value,duration_unit
0,s1,movie,Dick Johnson Is Dead,Kirsten Johnson,unknow,United States,2021-09-25,2020,pg-13,90 min,documentaries,"As her father nears the end of his life, filmm...",90,min
1,s2,tv show,Blood & Water,unknow,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,tv-ma,2 Seasons,"international tv shows, tv dramas, tv mysteries","After crossing paths at a party, a Cape Town t...",2,Seasons
2,s3,tv show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...","France, Belgium",2021-09-24,2021,tv-ma,1 Season,"crime tv shows, international tv shows, tv act...",To protect his family from a powerful drug lor...,1,Season
3,s4,tv show,Jailbirds New Orleans,unknow,unknow,Pakistan,2021-09-24,2021,tv-ma,1 Season,"docuseries, reality tv","Feuds, flirtations and toilet talk go down amo...",1,Season
4,s5,tv show,Kota Factory,unknow,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,tv-ma,2 Seasons,"international tv shows, romantic tv shows, tv ...",In a city of coaching centers known to train I...,2,Seasons
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,r,158 min,"cult movies, dramas, thrillers","A political cartoonist, a crime reporter and a...",158,min
8803,s8804,tv show,Zombie Dumb,unknow,unknow,Pakistan,2019-07-01,2018,tv-y7,2 Seasons,"kids' tv, korean tv shows, tv comedies","While living alone in a spooky town, a young g...",2,Seasons
8804,s8805,movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2019-11-01,2009,r,88 min,"comedies, horror movies",Looking to survive in a world taken over by zo...,88,min
8805,s8806,movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,pg,88 min,"children & family movies, comedies","Dragged from civilian life, a former superhero...",88,min
8806,s8807,movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,tv-14,111 min,"dramas, international movies, music & musicals",A scrappy but poor boy worms his way into a ty...,111,min